### ISSUE TITLE
fail on Oracle db connection from RelStorage / zodbshootout

### ISSUE THREAD

**Issue by fiterbek** [zodb/zodbshootout#2]
Hi,

We are in the process of benchmarking several database types in a networked setup to see which is best suited for our needs, as we would like to migrate from ZEO to RelStorage.

So basically I installed cx_Oracle following the documentation in http://cx-oracle.sourceforge.net/BUILD.txt, adapted the oracle-home path to the correct path on my client machine. 
Since I'm running debian squeeze 64 bit, I installed the sdk and basic libraries from http://www.oracle.com/technetwork/topics/linux-amd64-093390.html (instantclient10_1).  

After trying to connect to the remote Oracle db directly from python using cx_Oracle (which works), I tried doing the same using zodbshootout. 

Since there is no mention in the documentation as to what format the dsn string should have, I tried several (which all work fine when used directly from python):
dsn //hostname:port/serviceid 
dsn user/pass@//hostname:port/serviceid
dsn (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=hostname)(PORT=port)))(CONNECT_DATA=(SID=servicename)))

and more variations (quoted and unquoted etc), all of which do not work and lead to the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/test/zodbshootout-0.5/src/zodbshootout/main.py", line 78, in populate
    db = db_factory()
  File "/opt/buildouts/.buildout/eggs/ZODB3-3.10.5-py2.6-linux-x86_64.egg/ZODB/config.py", line 101, in open
    storage = section.storage.open()
  File "/opt/buildouts/.buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/config.py", line 33, in open
    return RelStorage(adapter, name=config.name, options=options)
  File "/opt/buildouts/.buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/storage.py", line 167, in __init__
    self._adapter.schema.prepare()
  File "/opt/buildouts/.buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/adapters/schema.py", line 1086, in prepare
    self.connmanager.open_and_call(callback)
  File "/opt/buildouts/.buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/adapters/connmanager.py", line 73, in open_and_call
    conn, cursor = self.open()
  File "/opt/buildouts/.buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/adapters/oracle.py", line 302, in open
    self._user, self._password, self._dsn, **kw)
InterfaceError: Unable to acquire Oracle environment handle
```

I also tried setting the dsn string directly in the oracle.py file where the dsn is created but that didn't help either. 

What am I doing wrong? Is it a syntax problem? And if so, what is the correct syntax for accessing an Oracle db from a zodbshootout .conf file? 

It is so weird that I can connect from python directly but not indirectly from zodbshootout... Any help would be greatly appreciated.

**Comment by fiterbek** [comment]
cx_oracle version 5.1.2, python 2.6, RelStorage 1.5.1, Oracle server 11.2.04

**Comment by jamadden** [comment]
This is a config file I use to run the tests against an Oracle Developer Days Virtual Box VM:

```
%import relstorage
 <zodb main>
      <relstorage>
                name xyz
                read-only false
                keep-history true
                blob-chunk-size 10MB
                <oracle>
                  user relstoragetest
                  password relstoragetest
                  dsn 192.168.1.131/orcl
                </oracle>
       </relstorage>
</zodb>
```

The `ORACLE_HOME` environment variable also has to be correctly set.

**Comment by jamadden** [comment]
Closing because this is really a relstorage issue, not zodbshootout specific. If this is still an issue, please either open an issue in the zodb/relstorage repo, or try asking on the ZODB mailing list.
