### ISSUE TITLE
Why does the buildout have version pins for ZEO and ZODB?

### ISSUE THREAD

**Issue by jimfulton** [zodb/zodbshootout#25]
These cause shootout to fail because of the changes in transaction.

Is there any reason to pin these? (Or RelStorage for that matter.)

**Comment by jamadden** [comment]
I imagine they are pinned for repeatability. However, the set of version pins is incomplete, as you noted: transaction is missing, as is BTrees, among others.

The buildout configuration is sporadically maintained, at best.

**Comment by jimfulton** [comment]
FTR, as is, the buildout produces a shootout that fails to actually run. :)

I find shootout to be a pain to run whenever I try.

This time I had more success with pip, not because pip, but because that documentation promised less.

I suspect that it would be best to get rid of the buildout config and generally de emphasize any sort of turn-key install-and-run use of shootout, but rather document how to use it in a more manual fashion.
