### ISSUE TITLE
Simplify ZEO tests by using ZEO.server to manage ZEO servers

### ISSUE THREAD

**Issue by jimfulton** [zodb/zodbshootout#8]
There's no real need to manage ZEO servers externally (e.g. with supervisord).

BTW, you may want to consider switching from supervisord to zdaemon, which has been ported to Python 3 and for which there are helper buildout recipes.

**Comment by jamadden** [comment]
Thanks. I believe we need to stick with supervisord for mysql because of the way mysql handles signals---we have to use pidproxy. Because of that, I think it makes sense to stick with supervisord for everything.
